.TH BOMBARDIER 6 "Version 0.8.3" "Gergely Risko"

.SH NAME
bombardier \- the GNU Bombing utility

.SH SYNOPSIS
.TP 6
\fBbombardier\fP

.SH DESCRIPTION
\fBbombardier\fP is the GNU Bombing utility.

This was one of my favourite games on Commodore Plus 4 when I was I
child.  Your task is to bomb down cities. This can be done with a 3
character wide airplane, which can drop 3 character tall bombs to the
ugly # based houses.  If you can bomb down all of the houses you can
land with your plane, and in this case the challenge will continue on
the next city.  Good luck!

.SH COMMANDS
\fIspace\fP - drops a bomb
.br
\fIp\fP - pauses the game
.br
\fIq\fP - quits from the game
.br
\fI1..9\fP - sets the speed of the game

.SH FILES
.TP 10
\fI/var/games/bombardier/bdscore\fP
The shared best score file.

.SH AUTHORS
Gergely Risko <gergely@risko.hu>

.SH VERSION
Version 0.8.3 released on 2009-10-10

.SH BUGS
Should be reported to Debian BTS, http://bugs.debian.org/bombardier
