.TH BOMBARDIER 6 "Version 0.8" "RISKO Gergely"

.SH NAME
bombardier \- the GNU Bombing utility

.SH SYNOPSIS
.TP 6
\fBbombardier\fP

.SH DESCRIPTION
\fBbombardier\fP is the GNU Bombing utility for POSIX Un*xes.
This was one of my favourite games on Commod*re Pl*s 4 when I was I child.
Your task is to bomb down cities. This can be done with a 3 character wide 
curses airplane, which can drop 3 character tall bombs to the ugly # based
houses :-) If you can bomb down all of the houses you can land with your
plane, and in this case the program will continue on the second city.
Good luck!

.SH COMMANDS
\fIspace\fP - drop a bomb
.br
\fIp\fP - pause the game
.br
\fIq\fP - quit from the game
.br
\fI1..9\fP - set the speed of the game

.SH FILES
.TP 10
\fI/var/games/bombardier/bdscore\fP
The shared best score file.

.SH AUTHORS
RISKO Gergely <risko@debian.org>

.SH THANKS
.TP
.I To the original bombardier programmers.
I don't know their names, but I wanna. So guys! If you know, who did the 
bombardier for Commodore Plus 4, please write me.
.TP
.I Jochen Voss <voss@mathematik.uni-kl.de>
To the author of moon-buggy, because it is an other good console game.
.TP
.I LENART Janos <ocsi@irisz.hu>
For the idea. And for testing, bug reports.
.TP
.I Thimo Neubauer <thimo@debian.org>
For alpha helps.
.TP
.I RISKO Peter <rpetike@freemail.hu>
He gave me the original idea of console games, and he found the moon-buggy 
in debian potato. For lot of testing and bug reports about version 0.1 and 
later.
.TP
.I Linus Torvalds
For my OS.
.TP
.I All Debian folks
For the best distribution.

.SH VERSION
Version 0.8 released at 2001. 07. 21. 20:00 +0200

.SH BUGS
Should be reported to RISKO Gergely <risko@debian.org>
